import type { FormSchemaData } from '../types/formBuilder';

/**
 * AI Smart Form Generator Engine
 * Converts natural language prompt (English or Bangla) into a complete,
 * bilingual, multi-section institutional form schema.
 */
export function generateFormSchemaWithAI(userPrompt: string): FormSchemaData {
  const prompt = userPrompt.toLowerCase().trim();

  // 1. Science Fair / Event Registration
  if (prompt.includes('science') || prompt.includes('বিজ্ঞান') || prompt.includes('fair') || prompt.includes('event') || prompt.includes('মেলার')) {
    return {
      title: 'বার্ষিক বিজ্ঞান মেলা ও প্রজেক্ট প্রদর্শনী নিবন্ধন ফরম (Annual Science Fair Registration)',
      sub_title: 'BSISC Annual Science & Innovation Fair 2026',
      school_name: "Baridhara Scholars' International School and College (BSISC)",
      school_id: '1005',
      post_payment_document: 'Project Entry Token & Participant Slip',
      layout_style: 'wizard',
      sections: [
        {
          id: 'sec_sci_participant',
          section_key: 'team_leader_info',
          name_en: '1. Team Leader & Member Details',
          name_bn: '১. দলনেতা ও সদস্যদের বিবরণ',
          title_en: '1. Team Leader & Member Details',
          title_bn: '১. দলনেতা ও সদস্যদের বিবরণ',
          icon: 'Users',
          order: 1,
          fields: [
            {
              id: 'f_sci_leader_name',
              field_key: 'team_leader_name',
              key: 'team_leader_name',
              category: 'TEAM_INFO',
              label_en: 'Team Leader Full Name',
              label_bn: 'দলনেতার পূর্ণ নাম',
              type: 'text',
              placeholder: 'Enter student full name',
              required: true,
              visible: true,
              profile_sync: 'name',
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_sci_class_sec',
              field_key: 'class_section_roll',
              key: 'class_section_roll',
              category: 'TEAM_INFO',
              label_en: 'Class, Section & Roll No',
              label_bn: 'শ্রেণি, শাখা ও রোল নম্বর',
              type: 'text',
              placeholder: 'e.g. Class IX-A, Roll: 05',
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_sci_mobile',
              field_key: 'contact_mobile',
              key: 'contact_mobile',
              category: 'TEAM_INFO',
              label_en: 'Contact Mobile No (SMS Updates)',
              label_bn: 'যোগাযোগের সক্রিয় মোবাইল নম্বর',
              type: 'tel',
              placeholder: '01XXXXXXXXX',
              required: true,
              visible: true,
              profile_sync: 'phone',
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_sci_member_count',
              field_key: 'total_team_members',
              key: 'total_team_members',
              category: 'TEAM_INFO',
              label_en: 'Total Team Members',
              label_bn: 'দলের মোট সদস্য সংখ্যা',
              type: 'select',
              options: [
                { label_en: 'Solo Participant (১ জন)', label_bn: '১ জন (একক)', value: '1' },
                { label_en: '2 Members Team (২ জন)', label_bn: '২ জন', value: '2' },
                { label_en: '3 Members Team (৩ জন)', label_bn: '৩ জন', value: '3' },
                { label_en: '4 Members Team (৪ জন)', label_bn: '৪ জন', value: '4' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
          ],
        },
        {
          id: 'sec_sci_project',
          section_key: 'project_details',
          name_en: '2. Science Project Description',
          name_bn: '২. বিজ্ঞান প্রজেক্টের বিস্তারিত বিবরণ',
          title_en: '2. Science Project Description',
          title_bn: '২. বিজ্ঞান প্রজেক্টের বিস্তারিত বিবরণ',
          icon: 'Sparkles',
          order: 2,
          fields: [
            {
              id: 'f_sci_title',
              field_key: 'project_title',
              key: 'project_title',
              category: 'PROJECT_INFO',
              label_en: 'Project Title / Topic Name',
              label_bn: 'প্রজেক্টের শিরোনাম বা বিষয়',
              type: 'text',
              placeholder: 'e.g. Smart IoT Earthquake Alert System',
              required: true,
              visible: true,
              grid_col: 12,
              col_width: 12,
            },
            {
              id: 'f_sci_category',
              field_key: 'project_category',
              key: 'project_category',
              category: 'PROJECT_INFO',
              label_en: 'Scientific Category / Theme',
              label_bn: 'প্রজেক্টের ক্যাটাগরি বা থিম',
              type: 'select',
              options: [
                { label_en: 'Robotics & Artificial Intelligence (AI)', label_bn: 'রোবটিক্স ও এআই', value: 'robotics' },
                { label_en: 'Renewable Energy & Environmental Science', label_bn: 'নবায়নযোগ্য শক্তি ও পরিবেশ', value: 'environment' },
                { label_en: 'Applied Physics & Mechanical Engineering', label_bn: 'পদার্থবিজ্ঞান ও মেকানিক্স', value: 'physics' },
                { label_en: 'Biotechnology & Health Sciences', label_bn: 'বায়োটেকনোলজি ও স্বাস্থ্য', value: 'bio' },
                { label_en: 'Mobile App & Software Innovation', label_bn: 'সফটওয়্যার ও অ্যাপ ইনোভেশন', value: 'software' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_sci_power_req',
              field_key: 'power_plug_needed',
              key: 'power_plug_needed',
              category: 'PROJECT_INFO',
              label_en: 'Electricity / AC Power Plug Required in Booth?',
              label_bn: 'প্রদর্শনী বুথে বিদ্যুৎ সংযোগ (AC Power) প্রয়োজন কি?',
              type: 'select',
              options: [
                { label_en: 'Yes (হ্যাঁ, প্রয়োজন)', label_bn: 'হ্যাঁ', value: 'yes' },
                { label_en: 'No (ব্যাটারি চালিত বা প্রয়োজন নেই)', label_bn: 'না', value: 'no' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_sci_abstract',
              field_key: 'project_abstract_summary',
              key: 'project_abstract_summary',
              category: 'PROJECT_INFO',
              label_en: 'Project Summary & Practical Utilities',
              label_bn: 'প্রজেক্টের মূল ভাব ও বাস্তব জীবনের উপযোগিতা',
              type: 'textarea',
              placeholder: 'Describe what problem your project solves and how it functions...',
              required: true,
              visible: true,
              grid_col: 12,
              col_width: 12,
            },
          ],
        },
        {
          id: 'sec_sci_docs',
          section_key: 'diagram_proposal_docs',
          name_en: '3. Project Abstract & Diagram (PDF/Image)',
          name_bn: '৩. প্রজেক্টের সারসংক্ষেপ ও ডায়াগ্রাম সংযুক্তি',
          title_en: '3. Project Abstract & Diagram (PDF/Image)',
          title_bn: '৩. প্রজেক্টের সারসংক্ষেপ ও ডায়াগ্রাম সংযুক্তি',
          icon: 'Paperclip',
          order: 3,
          fields: [
            {
              id: 'f_sci_doc_pdf',
              field_key: 'project_abstract_pdf',
              key: 'project_abstract_pdf',
              category: 'DOCS',
              label_en: 'Detailed Project Proposal / Abstract File (PDF)',
              label_bn: 'প্রজেক্টের বিস্তারিত প্রস্তাবনা ফাইল (PDF)',
              type: 'file',
              required: false,
              visible: true,
              grid_col: 12,
              col_width: 12,
            },
          ],
        },
      ],
    };
  }

  // 2. Transfer Certificate (TC) / Certificate Request
  if (prompt.includes('tc') || prompt.includes('transfer') || prompt.includes('certificate') || prompt.includes('সনদ') || prompt.includes('ছাড়পত্র')) {
    return {
      title: 'ছাড়পত্র ও প্রশংসাপত্র আবেদন ফরম (Transfer Certificate & Testimonial Form)',
      sub_title: 'Student Official Documentation Request Portal',
      school_name: "Baridhara Scholars' International School and College (BSISC)",
      school_id: '1005',
      post_payment_document: 'TC / Certificate Application Slip',
      layout_style: 'wizard',
      sections: [
        {
          id: 'sec_tc_student',
          section_key: 'student_academic_records',
          name_en: '1. Student Academic Records',
          name_bn: '১. শিক্ষার্থীর একাডেমিক তথ্যাবলী',
          title_en: '1. Student Academic Records',
          title_bn: '১. শিক্ষার্থীর একাডেমিক তথ্যাবলী',
          icon: 'User',
          order: 1,
          fields: [
            {
              id: 'f_tc_name',
              field_key: 'student_full_name',
              key: 'student_full_name',
              category: 'STUDENT_INFO',
              label_en: 'Student Full Name (English)',
              label_bn: 'শিক্ষার্থীর পূর্ণ নাম (ইংরেজিতে)',
              type: 'text',
              required: true,
              visible: true,
              profile_sync: 'name',
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_tc_id',
              field_key: 'student_id_number',
              key: 'student_id_number',
              category: 'STUDENT_INFO',
              label_en: 'Student ID / Registration No',
              label_bn: 'শিক্ষার্থী আইডি / রেজিস্ট্রেশন নম্বর',
              type: 'text',
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_tc_last_class',
              field_key: 'last_attended_class',
              key: 'last_attended_class',
              category: 'STUDENT_INFO',
              label_en: 'Last Attended Class & Section',
              label_bn: 'সর্বশেষ অধ্যয়নকৃত শ্রেণি ও শাখা',
              type: 'text',
              placeholder: 'e.g. Class IX (Science-A)',
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_tc_doc_type',
              field_key: 'requested_document_type',
              key: 'requested_document_type',
              category: 'REQUEST_INFO',
              label_en: 'Requested Document Type',
              label_bn: 'প্রার্থিত কাগজপত্রের ধরন',
              type: 'select',
              options: [
                { label_en: 'Transfer Certificate (ছাড়পত্র / টিসি)', label_bn: 'ছাড়পত্র (টিসি)', value: 'tc' },
                { label_en: 'Academic Testimonial / Character Certificate (প্রশংসাপত্র)', label_bn: 'প্রশংসাপত্র', value: 'testimonial' },
                { label_en: 'Official Academic Transcript (নম্বরপত্র)', label_bn: 'অফিসিয়াল ট্রান্সক্রিপ্ট', value: 'transcript' },
                { label_en: 'Medium of Instruction Certificate (ইংরেজি মাধ্যম প্রত্যয়ন)', label_bn: 'মিডিয়াম অব ইনস্ট্রাকশন সনদ', value: 'medium_cert' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
          ],
        },
        {
          id: 'sec_tc_reason',
          section_key: 'reason_and_clearance',
          name_en: '2. Reason for Leaving & Dues Clearance',
          name_bn: '২. ছাড়পত্রের কারণ ও বকেয়া সংক্রান্ত তথ্য',
          title_en: '2. Reason for Leaving & Dues Clearance',
          title_bn: '২. ছাড়পত্রের কারণ ও বকেয়া সংক্রান্ত তথ্য',
          icon: 'FileText',
          order: 2,
          fields: [
            {
              id: 'f_tc_reason_desc',
              field_key: 'reason_for_leaving',
              key: 'reason_for_leaving',
              category: 'REASON_INFO',
              label_en: 'Reason for Transfer / Leaving Institution',
              label_bn: 'প্রতিষ্ঠান ত্যাগের কারণ',
              type: 'select',
              options: [
                { label_en: "Guardian Transfer / Relocation (অভিভাবকের কর্মস্থল বদলি)", label_bn: 'অভিভাবকের বদলি', value: 'guardian_transfer' },
                { label_en: 'Change of Residence (বাসা পরিবর্তন)', label_bn: 'বাসা পরিবর্তন', value: 'residence_change' },
                { label_en: 'Admission to Cadet College / Other School', label_bn: 'ক্যাডেট কলেজ/অন্যান্য প্রতিষ্ঠানে সুযোগ', value: 'cadet_admission' },
                { label_en: 'Going Abroad (বিদেশে গমন)', label_bn: 'বিদেশে গমন', value: 'abroad' },
                { label_en: 'Other Reason (অন্যান্য)', label_bn: 'অন্যান্য কারণ', value: 'other' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_tc_destination',
              field_key: 'destination_school_name',
              key: 'destination_school_name',
              category: 'REASON_INFO',
              label_en: 'Target School / Institution Name',
              label_bn: 'পরবর্তী শিক্ষাপ্রতিষ্ঠানের নাম',
              type: 'text',
              placeholder: 'Name of new school/college',
              required: false,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_tc_clearance_file',
              field_key: 'accounts_library_clearance_receipt',
              key: 'accounts_library_clearance_receipt',
              category: 'DOCS',
              label_en: 'Tuition Fee & Library Clearance Slip (PDF/JPG)',
              label_bn: 'বেতন পরিশোধ ও লাইব্রেরি ক্লিয়ারেন্স রসিদ',
              type: 'file',
              required: false,
              visible: true,
              grid_col: 12,
              col_width: 12,
            },
          ],
        },
      ],
    };
  }

  // 3. Transport / School Bus Service
  if (prompt.includes('transport') || prompt.includes('bus') || prompt.includes('বাস') || prompt.includes('পরিবহন')) {
    return {
      title: 'স্কুল বাস ও পরিবহন সেবা আবেদন ফরম (School Transport & Bus Service Form)',
      sub_title: 'Student Safe Transit & Route Allocation Portal',
      school_name: "Baridhara Scholars' International School and College (BSISC)",
      school_id: '1005',
      post_payment_document: 'Bus Pass Card & Route Allocation Voucher',
      layout_style: 'wizard',
      sections: [
        {
          id: 'sec_bus_student',
          section_key: 'student_transport_info',
          name_en: '1. Student & Guardian Info',
          name_bn: '১. শিক্ষার্থী ও অভিভাবকের তথ্য',
          title_en: '1. Student & Guardian Info',
          title_bn: '১. শিক্ষার্থী ও অভিভাবকের তথ্য',
          icon: 'User',
          order: 1,
          fields: [
            {
              id: 'f_bus_student_name',
              field_key: 'student_name',
              key: 'student_name',
              category: 'STUDENT_INFO',
              label_en: 'Student Full Name',
              label_bn: 'শিক্ষার্থীর পূর্ণ নাম',
              type: 'text',
              required: true,
              visible: true,
              profile_sync: 'name',
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_bus_student_id',
              field_key: 'student_id',
              key: 'student_id',
              category: 'STUDENT_INFO',
              label_en: 'Student ID / Class Roll',
              label_bn: 'শিক্ষার্থী আইডি / রোল',
              type: 'text',
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_bus_mobile',
              field_key: 'emergency_mobile_no',
              key: 'emergency_mobile_no',
              category: 'STUDENT_INFO',
              label_en: 'Emergency Contact Mobile No',
              label_bn: 'জরুরি যোগাযোগের মোবাইল নম্বর',
              type: 'tel',
              placeholder: '01XXXXXXXXX',
              required: true,
              visible: true,
              profile_sync: 'phone',
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_bus_shift',
              field_key: 'school_shift',
              key: 'school_shift',
              category: 'STUDENT_INFO',
              label_en: 'School Shift',
              label_bn: 'শিফট নির্বাচন করুন',
              type: 'select',
              options: [
                { label_en: 'Morning Shift (প্রভাতি)', label_bn: 'প্রভাতি শিফট', value: 'morning' },
                { label_en: 'Day Shift (দিবা)', label_bn: 'দিবা শিফট', value: 'day' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
          ],
        },
        {
          id: 'sec_bus_route',
          section_key: 'route_and_stoppage',
          name_en: '2. Route & Stoppage Selection',
          name_bn: '২. রুট ও স্টপেজ নির্বাচন',
          title_en: '2. Route & Stoppage Selection',
          title_bn: '২. রুট ও স্টপেজ নির্বাচন',
          icon: 'MapPin',
          order: 2,
          fields: [
            {
              id: 'f_bus_route_no',
              field_key: 'preferred_bus_route',
              key: 'preferred_bus_route',
              category: 'ROUTE_INFO',
              label_en: 'Select Transport Route',
              label_bn: 'পরিবহন রুট নির্বাচন করুন',
              type: 'select',
              options: [
                { label_en: 'Route 1: Uttara - Airport - Baridhara', label_bn: 'রুট ১: উত্তরা - এয়ারপোর্ট - বারিধারা', value: 'route_1' },
                { label_en: 'Route 2: Mirpur - ECB - Kalshi - BSISC', label_bn: 'রুট ২: মিরপুর - ইসিবি - কালশী - বিএসআইএসসি', value: 'route_2' },
                { label_en: 'Route 3: Gulshan - Badda - Kuril - Campus', label_bn: 'রুট ৩: গুলশান - বাড্ডা - কুড়িল - ক্যাম্পাস', value: 'route_3' },
                { label_en: 'Route 4: Banani - Mohakhali - DOHS - BSISC', label_bn: 'রুট ৪: বনানী - মহাখালী - ডিওএইচএস', value: 'route_4' },
                { label_en: 'Route 5: Rampura - Khilgaon - Bashundhara', label_bn: 'রুট ৫: রামপুরা - খিলগাঁও - বসুন্ধরা', value: 'route_5' },
              ],
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_bus_stoppage',
              field_key: 'pickup_drop_stoppage',
              key: 'pickup_drop_stoppage',
              category: 'ROUTE_INFO',
              label_en: 'Exact Pickup / Drop Stoppage Name',
              label_bn: 'নির্দিষ্ট পিকআপ / ড্রপ স্টপেজের নাম',
              type: 'text',
              placeholder: 'e.g. Uttara Sector 7 House Building',
              required: true,
              visible: true,
              grid_col: 6,
              col_width: 6,
            },
            {
              id: 'f_bus_address',
              field_key: 'residence_full_address',
              key: 'residence_full_address',
              category: 'ROUTE_INFO',
              label_en: 'Current Residential Full Address',
              label_bn: 'বর্তমান বাসস্থানের পূর্ণ ঠিকানা',
              type: 'textarea',
              placeholder: 'House, Road, Block, Area details...',
              required: true,
              visible: true,
              grid_col: 12,
              col_width: 12,
            },
          ],
        },
      ],
    };
  }

  // 4. Default Smart Generated Custom Form from user prompt
  const cleanedTitle = userPrompt
    ? `${userPrompt.slice(0, 60)} (AI Generated Form)`
    : 'কাস্টম স্মার্ট ফর্ম (AI Generated Dynamic Form)';

  return {
    title: cleanedTitle,
    sub_title: 'Institutional Smart Online Application Portal',
    school_name: "Baridhara Scholars' International School and College (BSISC)",
    school_id: '1005',
    post_payment_document: 'Application Voucher & Acknowledgment Slip',
    layout_style: 'wizard',
    sections: [
      {
        id: 'sec_ai_applicant',
        section_key: 'applicant_information',
        name_en: '1. Applicant Information',
        name_bn: '১. আবেদনকারীর পরিচিতি',
        title_en: '1. Applicant Information',
        title_bn: '১. আবেদনকারীর পরিচিতি',
        icon: 'User',
        order: 1,
        fields: [
          {
            id: 'f_ai_full_name',
            field_key: 'applicant_full_name',
            key: 'applicant_full_name',
            category: 'GENERAL_INFO',
            label_en: 'Full Name (English / Bangla)',
            label_bn: 'পূর্ণ নাম (ইংরেজি বা বাংলায়)',
            type: 'text',
            placeholder: 'Enter your full name',
            required: true,
            visible: true,
            profile_sync: 'name',
            grid_col: 6,
            col_width: 6,
          },
          {
            id: 'f_ai_mobile',
            field_key: 'contact_mobile',
            key: 'contact_mobile',
            category: 'GENERAL_INFO',
            label_en: 'Active Contact Mobile No',
            label_bn: 'সক্রিয় যোগাযোগ মোবাইল নম্বর',
            type: 'tel',
            placeholder: '01XXXXXXXXX',
            required: true,
            visible: true,
            profile_sync: 'phone',
            grid_col: 6,
            col_width: 6,
          },
          {
            id: 'f_ai_email',
            field_key: 'contact_email',
            key: 'contact_email',
            category: 'GENERAL_INFO',
            label_en: 'Email Address',
            label_bn: 'ইমেইল ঠিকানা',
            type: 'email',
            placeholder: 'user@example.com',
            required: false,
            visible: true,
            profile_sync: 'email',
            grid_col: 6,
            col_width: 6,
          },
          {
            id: 'f_ai_category',
            field_key: 'applicant_category',
            key: 'applicant_category',
            category: 'GENERAL_INFO',
            label_en: 'Category / Selection Group',
            label_bn: 'ক্যাটাগরি বা গ্রুপ নির্বাচন',
            type: 'select',
            options: [
              { label_en: 'General / Regular (সাধারণ)', label_bn: 'সাধারণ', value: 'general' },
              { label_en: 'Special Priority (অগ্রাধিকার)', label_bn: 'অগ্রাধিকার', value: 'priority' },
              { label_en: 'Institutional / Internal (অভ্যন্তরীণ)', label_bn: 'অভ্যন্তরীণ', value: 'internal' },
            ],
            required: true,
            visible: true,
            grid_col: 6,
            col_width: 6,
          },
        ],
      },
      {
        id: 'sec_ai_details',
        section_key: 'application_details',
        name_en: '2. Application Requirements & Details',
        name_bn: '২. আবেদনের মূল বিষয়বস্তু ও বিবরণ',
        title_en: '2. Application Requirements & Details',
        title_bn: '২. আবেদনের মূল বিষয়বস্তু ও বিবরণ',
        icon: 'FileText',
        order: 2,
        fields: [
          {
            id: 'f_ai_subject',
            field_key: 'application_subject',
            key: 'application_subject',
            category: 'DETAILS_INFO',
            label_en: 'Purpose / Main Objective',
            label_bn: 'আবেদনের উদ্দেশ্য বা বিষয়',
            type: 'text',
            placeholder: 'State the primary purpose of this submission...',
            required: true,
            visible: true,
            grid_col: 12,
            col_width: 12,
          },
          {
            id: 'f_ai_statement',
            field_key: 'detailed_statement',
            key: 'detailed_statement',
            category: 'DETAILS_INFO',
            label_en: 'Detailed Description / Proposal',
            label_bn: 'বিস্তারিত বক্তব্য বা প্রস্তাবনা',
            type: 'textarea',
            placeholder: 'Provide thorough background, arguments or descriptions...',
            required: true,
            visible: true,
            grid_col: 12,
            col_width: 12,
          },
          {
            id: 'f_ai_date',
            field_key: 'effective_date',
            key: 'effective_date',
            category: 'DETAILS_INFO',
            label_en: 'Effective / Preferred Date',
            label_bn: 'কার্যকরের তারিখ',
            type: 'date',
            required: false,
            visible: true,
            grid_col: 6,
            col_width: 6,
          },
          {
            id: 'f_ai_attachment',
            field_key: 'supporting_attachment_file',
            key: 'supporting_attachment_file',
            category: 'DOCS',
            label_en: 'Supporting Documents / Verification PDF',
            label_bn: 'প্রয়োজনীয় কাগজপত্র সংযুক্তি (PDF/JPG)',
            type: 'file',
            required: false,
            visible: true,
            grid_col: 6,
            col_width: 6,
          },
        ],
      },
    ],
  };
}